### ISSUE TITLE
论文标签

### ISSUE THREAD

**Issue by yufengwhy** [endymecy/awesome-deeplearning-resources#5]
非常好的东西，赞赞赞。
一个小问题，有的paper（COMPOSITIONAL ATTENTION NETWORKS FOR MACHINE REASONING）挂arXiv后被会议ICLR等接收，能不能更新一个ICLR的标签？好paper确实太多了，可以挂一些[顶会标签](http://history.ccf.org.cn/sites/ccf/biaodan.jsp?contentId=2903940690839)

**Comment by endymecy** [comment]
从头开始整理工作量太大，不过后续可以有这个操作。当然，您可以把您知道的顶会论文提request
